CREATE TABLE `backup_deletion_log` (
    `deletion_id` bigint NOT NULL AUTO_INCREMENT,
    `table_name` varchar(64) NOT NULL,
    `record_key` json NOT NULL,
    `deleted_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`deletion_id`),
    KEY `idx_backup_deletion_window` (`table_name`, `deleted_at`, `deletion_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `player` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_player_backup_updated` (`updated_at`);
ALTER TABLE `session` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_session_backup_updated` (`updated_at`);
ALTER TABLE `available_player` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_available_player_backup_updated` (`updated_at`);
ALTER TABLE `court` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_court_backup_updated` (`updated_at`);
ALTER TABLE `team` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_team_backup_updated` (`updated_at`);
ALTER TABLE `shuttle_ball` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_shuttle_ball_backup_updated` (`updated_at`);
ALTER TABLE `game` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_game_backup_updated` (`updated_at`);
ALTER TABLE `game_shuttle_map` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_game_shuttle_map_backup_updated` (`updated_at`);
ALTER TABLE `service` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_service_backup_updated` (`updated_at`);
ALTER TABLE `rent_by_time` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_rent_by_time_backup_updated` (`updated_at`);
ALTER TABLE `debit` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_debit_backup_updated` (`updated_at`);
ALTER TABLE `debit_summary` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_debit_summary_backup_updated` (`updated_at`);
ALTER TABLE `payment` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_payment_backup_updated` (`updated_at`);
ALTER TABLE `payment_debit` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_payment_debit_backup_updated` (`updated_at`);
ALTER TABLE `inventory_item` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_inventory_item_backup_updated` (`updated_at`);
ALTER TABLE `purchase_lot` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_purchase_lot_backup_updated` (`updated_at`);
ALTER TABLE `stock_movement` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_stock_movement_backup_updated` (`updated_at`);
ALTER TABLE `role` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_role_backup_updated` (`updated_at`);
ALTER TABLE `app_user` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_app_user_backup_updated` (`updated_at`);
ALTER TABLE `app_user_role` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_app_user_role_backup_updated` (`updated_at`);
ALTER TABLE `refresh_token` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_refresh_token_backup_updated` (`updated_at`);
ALTER TABLE `invoice` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_invoice_backup_updated` (`updated_at`);
ALTER TABLE `invoice_item` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_invoice_item_backup_updated` (`updated_at`);
ALTER TABLE `invoice_series` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_invoice_series_backup_updated` (`updated_at`);
ALTER TABLE `bill_config` ADD COLUMN `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), MODIFY COLUMN `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD KEY `idx_bill_config_backup_updated` (`updated_at`);

CREATE TRIGGER `backup_delete_player` AFTER DELETE ON `player` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('player', JSON_OBJECT('player_id', OLD.`player_id`));
CREATE TRIGGER `backup_delete_session` AFTER DELETE ON `session` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('session', JSON_OBJECT('session_id', OLD.`session_id`));
CREATE TRIGGER `backup_delete_available_player` AFTER DELETE ON `available_player` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('available_player', JSON_OBJECT('ava_id', OLD.`ava_id`));
CREATE TRIGGER `backup_delete_court` AFTER DELETE ON `court` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('court', JSON_OBJECT('court_id', OLD.`court_id`));
CREATE TRIGGER `backup_delete_team` AFTER DELETE ON `team` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('team', JSON_OBJECT('team_id', OLD.`team_id`));
CREATE TRIGGER `backup_delete_shuttle_ball` AFTER DELETE ON `shuttle_ball` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('shuttle_ball', JSON_OBJECT('shuttle_id', OLD.`shuttle_id`));
CREATE TRIGGER `backup_delete_game` AFTER DELETE ON `game` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('game', JSON_OBJECT('game_id', OLD.`game_id`));
CREATE TRIGGER `backup_delete_game_shuttle_map` AFTER DELETE ON `game_shuttle_map` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('game_shuttle_map', JSON_OBJECT('id', OLD.`id`));
CREATE TRIGGER `backup_delete_service` AFTER DELETE ON `service` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('service', JSON_OBJECT('ser_id', OLD.`ser_id`));
CREATE TRIGGER `backup_delete_rent_by_time` AFTER DELETE ON `rent_by_time` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('rent_by_time', JSON_OBJECT('id', OLD.`id`));
CREATE TRIGGER `backup_delete_debit` AFTER DELETE ON `debit` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('debit', JSON_OBJECT('debit_id', OLD.`debit_id`));
CREATE TRIGGER `backup_delete_debit_summary` AFTER DELETE ON `debit_summary` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('debit_summary', JSON_OBJECT('debt_sum_id', OLD.`debt_sum_id`));
CREATE TRIGGER `backup_delete_payment` AFTER DELETE ON `payment` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('payment', JSON_OBJECT('payment_id', OLD.`payment_id`));
CREATE TRIGGER `backup_delete_payment_debit` AFTER DELETE ON `payment_debit` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('payment_debit', JSON_OBJECT('payment_debit_id', OLD.`payment_debit_id`));
CREATE TRIGGER `backup_delete_inventory_item` AFTER DELETE ON `inventory_item` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('inventory_item', JSON_OBJECT('item_id', OLD.`item_id`));
CREATE TRIGGER `backup_delete_purchase_lot` AFTER DELETE ON `purchase_lot` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('purchase_lot', JSON_OBJECT('lot_id', OLD.`lot_id`));
CREATE TRIGGER `backup_delete_stock_movement` AFTER DELETE ON `stock_movement` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('stock_movement', JSON_OBJECT('movement_id', OLD.`movement_id`));
CREATE TRIGGER `backup_delete_role` AFTER DELETE ON `role` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('role', JSON_OBJECT('role_id', OLD.`role_id`));
CREATE TRIGGER `backup_delete_app_user` AFTER DELETE ON `app_user` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('app_user', JSON_OBJECT('user_id', OLD.`user_id`));
CREATE TRIGGER `backup_delete_app_user_role` AFTER DELETE ON `app_user_role` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('app_user_role', JSON_OBJECT('user_id', OLD.`user_id`, 'role_id', OLD.`role_id`));
CREATE TRIGGER `backup_delete_refresh_token` AFTER DELETE ON `refresh_token` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('refresh_token', JSON_OBJECT('refresh_token_id', OLD.`refresh_token_id`));
CREATE TRIGGER `backup_delete_invoice` AFTER DELETE ON `invoice` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('invoice', JSON_OBJECT('invoice_id', OLD.`invoice_id`));
CREATE TRIGGER `backup_delete_invoice_item` AFTER DELETE ON `invoice_item` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('invoice_item', JSON_OBJECT('item_id', OLD.`item_id`));
CREATE TRIGGER `backup_delete_invoice_series` AFTER DELETE ON `invoice_series` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('invoice_series', JSON_OBJECT('series_key', OLD.`series_key`));
CREATE TRIGGER `backup_delete_bill_config` AFTER DELETE ON `bill_config` FOR EACH ROW INSERT INTO `backup_deletion_log` (`table_name`,`record_key`) VALUES ('bill_config', JSON_OBJECT('config_id', OLD.`config_id`));
